로그인 기능 구현 (인증, 인가)
devridge-team-project/devridge-server pull request #15
Opened 2024-01-09 09:40 UTC by Jungsu-lilly

## Description ✍️
* Spring Security를 사용해 로그인 기능을 구현했습니다.
* 회원 가입, 회원 탈퇴, 로그인, 로그아웃 API를 개발했습니다.
* JWT(Json Web Token) 방식으로 엑세스, 리프레시 토큰을 발급합니다.

## Screen Shot 📷
#### 사용자 인증 흐름도
![인증흐름요약](https://github.com/devridge-team-project/devridge-server/assets/56336436/af0dacde-025b-4b52-8ec9-fed2603b5638)

#### 인증 방식 : JWT(Json Web Token)
- 엑세스, 리프레시 토큰 발급
- 토큰 만료 시 서버에서 리프레시 토큰을 통해 유효성을 검사, 엑세스 토큰을 재발급합니다.

<br>

### 🚨 로그인 시, 메서드 호출 순서
> **로그인 성공 시**
1. JwtAuthanticationFilter - attemptAuthentication()
2. JwtAuthenticationFilter - authenticate()
3. CustomUserDetailsService - loadUserByUsername()
4. JwtAuthenticationFilter - successfulAuthentication()

인증 성공 후, SecurityContext 에 인증 정보(UsernamePasswordAuthenticationToken)가 저장됩니다.

> **로그인 실패 시**
1. JwtAuthenticationFilter - attemptAuthentication()
2. JwtAuthenticationProvider - authenticate()
3. CustomUserDetailsService - loadUserByUsername()
4. JwtAuthenticationFilter - unsuccessfulAuthentication()

인증 실패 후, AuthenticationFailuerHandler 가 실행됩니다.
<br>

## 테스트 시 유의사항 ⚠️
* API 명세서에 따라 테스트 부탁드립니다.
* 위에 설명드린 대로 시큐리티 실행 흐름을 파악하면 좋을 것 같습니다.

## Merge 전 체크 리스트 ✅
- [ ] Backend 컨벤션을 잘 지켰나요?
- [ ] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

2024-01-09 10:55 UTC, yu-heejin requested changes
전반적으로 리뷰 보시고 리뷰되지 않는 부분도 수정해주세요 :)

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/constant/MemberConstant.java
> +public interface MemberConstant {
추가적으로 아래의 상수들이 전역적으로 사용되지 않는다면 굳이 constant를 따로 만들지 않는 것이 유지보수하는데 더 좋은 것 같다고 생각하는데 이에 대한 의견도 궁금합니다.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/constant/SkillConstants.java
> +    static {
tempSet은 어떤 용도인가요? 저희 스킬셋은 DB에 저장하는 걸로 알고 있었는데..!

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/AbstractTimeEntity.java
> +public abstract class AbstractTimeEntity {
같은 클래스가 두 개 있네요? 삭제 부탁드립니다! 추후 BaseEntity를 사용해주세요 :)

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/controller/MemberController.java
> +    @PostMapping("/one")
상수와 어노테이션 사이 공백 추가해주세요!
또한, one이란 이름은 해당 엔드포인트의 목적을 명확하게 드러내지 않는 것 같습니다. 다른 이름으로 바꿔주시는 것은 어떤가요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/controller/MemberController.java
> +    public ResponseEntity<?> signUp(@Valid @RequestBody CreateMemberRequest reqDto) {
변수 이름에 Dto와 같은 자료형은 인코딩하지 않는 것이 좋습니다.
https://actumn.tistory.com/72

또한 추가적으로 reqDto같은 모호한 이름 대신 해당 dto가 어떤 request인지 명확하게 표시해주면 더 좋을 것 같네요!

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    private String provider = MemberConstant.PROVIDER_NORMAL;
이런 방식으로 default값을 넣는 것도 좋지만, 엔티티에서 `@ColumnDefault`를 사용하시는 것을 더 권장합니다 :)
requestDto는 프론트엔드에서 넘겨주는 값을 그대로 받아야 유효성 검증이 가능하기 때문입니다.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    private String password;
비밀번호같은 경우는 별다른 규칙이 없을까요? 영문, 숫자같은 규칙이요!

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    @NotBlank(message = "빈 이메일을 입력할 수 없습니다.")
해당 이메일이 이메일 형식인지 확인하는 유효성 검사를 추가하면 좋을 것 같아요.
https://dev-coco.tistory.com/124

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    public String toString() {
toString()은 사용하지 않는다면 삭제하는 것이 좋을 것 같네요.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    private String skills;
스킬셋은 문자로 받나요? 저라면 skill id 배열로 받을 것 같습니다.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    public String[] getSkills(){
이 메소드는 혹시 어디서 사용하나요? 다른 곳에서 사용한다면 서비스 레이어로 옮기는건 어떠신가요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/response/CreateMemberResponse.java
> +public class CreateMemberResponse {
create 시 response가 필요한가요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +@AllArgsConstructor
엔티티에 `@AllArgsConstructor`가 필요할까요? 저라면 데이터를 저장해야할 필드만 따로 생성자를 만들 것 같습니다.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +@NoArgsConstructor
@NoArgsConstructor 사용 시 접근 제한을 걸어두시면 좋습니다.
```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```
https://github.com/techeer-TIL-group/yu-heejin/blob/main/Spring/Entity%EC%97%90%EC%84%9C%20%EA%B8%B0%EB%B3%B8%20%EC%83%9D%EC%84%B1%EC%9E%90%EC%97%90%20Protected%EB%A5%BC%20%EC%84%A4%EC%A0%95%ED%95%98%EB%8A%94%20%EC%9D%B4%EC%9C%A0.md

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +@NoArgsConstructor
추가적으로 @SqlDelete를 사용하시면 저희 soft delete 기능을 쉽게 이용하실 수 있습니다.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +    @Column(name = "password", nullable = false)
[선택] 중요한건 아니지만 @NotNull로도 해당 엔티티의 유효성 검증이 가능합니다.
https://kafcamus.tistory.com/15

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +    @Column(name = "id", nullable = false)
모든 필드에 `@Column`을 다 추가하실 필요는 없을 것 같아요!

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/RefreshToken.java
> +    @JoinColumn(name = "member_id")
연관관계 매핑 시 지연 로딩을 사용하는 것을 추천드립니다.
https://ict-nroo.tistory.com/132

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/repository/RefreshTokenRepository.java
> +    @Query("select rf FROM RefreshToken rf WHERE rf.member.id = :memberId")
rf같은 모호한 단어대신 조금 더 명확한 단어를 사용해주세요.. 😅

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    private final MemberRepository memberRepository;
```suggestion

    private final MemberRepository memberRepository;
```
다른 클래스랑 컨벤션 맞춰서 클래스와 변수 사이에 개행 넣어주세요.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    @Transactional
`@Transactional` 연산은 사실 무거운(?) 연산이긴 합니다 😅
단순한 읽기의 경우 `@Transactional(readOnly = true)`를 사용하시면 좋아요.
또한 update, delete 쿼리일지라도 쿼리가 한 개 정도면 사용하지 않는 걸 추천드립니다.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    public void createMemberSkill(CreateMemberRequest reqDto, Member member) {
해당 메소드는 다른 레이어에서 사용하지 않는 것 같은데 private로 하면 어떨까요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        if(!areSkillsValid(reqDto.getSkills())){
```suggestion
        if (!areSkillsValid(reqDto.getSkills())) {
```

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        for (String userSkill : userSkills) {
frontend에서 유저 스킬 아이디 리스트 자체를 넘겨주면 findBy할 필요가 없을 것 같은데 어떻게 생각하시나요?
추가적으로 반복계 쿼리를 사용하는 것은 지양하는 것이 좋습니다 :)
https://velog.io/@walker/%EB%B0%98%EB%B3%B5%EA%B3%84%EC%99%80-%ED%8F%AC%EC%9E%A5%EA%B3%84

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        for (String userSkill : userSkills) {
이 부분은 추후 jdbc bulk insert로 바꿔주세요!

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        if (passwordEncoder.matches(reqDto.getPassword(), member.getPassword())){
객체지향적인 코드에서 else 문을 사용하는 것은 지양하고 있는 편이긴 합니다. 아래와 같이 수정하는 것은 어떠신가요?
```suggestion
        if (!passwordEncoder.matches(reqDto.getPassword(), member.getPassword())) {
           throw new PasswordNotMatchException();
        }
        
        // 아래에 이후 로직 작성
```

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/PasswordChecker.java
> +        if(password.length() < 5 || password.length() > 16){
```suggestion
        if (password.length() < 5 || password.length() > 16) {
```

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/PasswordChecker.java
> +        }
```suggestion
        }
        
```

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/skill/dto/request/CreateMemberSkillRequest.java
> +package org.devridge.api.domain.skill.dto.request;
안 쓰는 코드, 파일 등은 삭제해주세요.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/MemberSkill.java
> +    @ManyToOne
여기도 지연 로딩 해주시면 좋습니다!

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/MemberSkill.java
> +    private boolean isDeleted;
mysql에서 boolean 타입이 지원이 안돼서 아래 처럼 수정해주세요!
`@Column(name = "is_deleted", columnDefinition = "TINYINT(1)")`

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/exception/member/DuplEmailException.java
> +    private String message;
```suggestion
    private String message;
    
```

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/exception/member/SkillsNotValidException.java
> +@Getter
Exception에 Getter가 필요한 이유가 있을까요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/auth/CustomMemberDetails.java
> +@Getter
여기도 @Getter는 필요 없을 것 같슴다

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/config/SecurityConfig.java
> +        AuthenticationManager authenticationManager = authenticationManager(http.getSharedObject(AuthenticationConfiguration.class));
요기 뭔가 printWidth 120 넘어가는 것 같은데 맞을까요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/dto/TokenResponse.java
> +@Component
해당 dto에 컴포넌트 스캔이 필요한 이유는..?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/filter/JwtAuthenticationFilter.java
> +public class JwtAuthenticationFilter extends UsernamePasswordAuthenticationFilter {
여기 클래스도 위 리뷰들 참고하셔서 코드 스타일 수정해주세요~!

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/filter/JwtAuthorizationFilter.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException, UserPrincipalNotFoundException {
해당 메소드에 책임이 너무 많아보이는데, token 부분, 만료 확인 부분 등 로직을 따로 함수 추상화를 하시는 것은 어떤가요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/filter/JwtAuthorizationFilter.java
> +            return true;
return true;가 중복되는데 혹시 괜찮은 방법 없을까요>...

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/util/AccessTokenUtil.java
> +        }else return null;
return이 있으면 else는 사용하지 않아도 괜찮습니다.

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/util/JwtUtil.java
> +    private static long TOKEN_VALIDITY_TIME_IN_SECONDS = 1000;
궁금한 부분이 있는데 이 부분을 모두 정적(static)으로 선언하신 이유가 있나요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/util/JwtUtil.java
> +    private static Map<String, Object> createAccessTokenClaims(Member member, Long refreshTokenId) {
이 부분은 혹시 map 대신 dto로 교체할 수 없을까요... 🤔🤔

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/util/ResponseUtil.java
> +    public static void createResponseMessage(HttpServletResponse response, BaseResponse baseResponse) throws StreamWriteException, DatabindException, IOException {
해당 클래스는 혹시 어떤 용도일까요?

2024-01-09 10:55 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/util/SecurityContextHolderUtil.java
> +@Component
static을 사용하면 컴포넌트 스캔은 필요 없지 않을까요?

2024-01-09 10:55 UTC, yu-heejin commented on build.gradle
> +        implementation 'org.springframework.boot:spring-boot-starter-security'
해당 의존성이 global하게 쓰이는 것이 아니라면, api 모듈로 이동하는 것도 괜찮아보입니다.

2024-01-09 12:44 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/AbstractTimeEntity.java
> +public abstract class AbstractTimeEntity {
넵 확인했습니다.

2024-01-09 12:47 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/config/CustomCorsConfig.java
> +    public void addCorsMappings(CorsRegistry registry){
확인했습니다! 코드 컨벤션 좀더 신경쓸게요🤣

2024-01-09 13:34 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/constant/MemberConstant.java
> +public interface MemberConstant {
현재 봤을 때  특정 클래스나 모듈에만 국한되어 사용되어서, 해당 클래스 내부에 정의하는 게 좀 더 직관적일 것 같네요!
상수가 전역적으로 사용되지 않는다면, 각각의 상수를 사용하는 클래스 내에 정해서 쓰는게 유지보수가 더 쉬울 것 같아요

해당 클래스가 후에 전역적으로 사용되면 ENUM 클래스로 만들어 추가하는걸로 하겠습니다.
현재는 지울게요!

2024-01-09 13:39 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/config/JpaConfig.java
> +package org.devridge.api.config;
AbstractTimeEntity 클래스에 
@CreatedDate, @LastModifiedDate 어노테이션과 함께 JPA Auditing을 활성화하기 위한 설정 클래스입니다!

위 설정 클래스가 없으니까 엔티티 생성할 때 에러가 발생하더라구요.

JpaConfig 클래스가 @EnableJpaAuditing 어노테이션을 통해 JPA Auditing 기능을 활성화합니다. 
이를 통해 AbstractTimeEntity 클래스에서 정의된 createdAt, updatedAt 필드가 엔터티의 생명주기에 따라 자동으로 관리된다고 합니다.

이 클래스를 프로젝트에 추가하면, 스프링 부트가 애플리케이션을 시작할 때 JPA Auditing 기능을 활성화하고, AbstractTimeEntity를 상속받는 엔터티 클래스들에서 createdAt 및 updatedAt 필드가 자동으로 채워진다고 해요

2024-01-09 13:40 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/config/JpaConfig.java
> +package org.devridge.api.config;
AbstractTimeEntity 가 추후에 삭제되면 손보겠습니다.

2024-01-09 13:40 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/config/CustomCorsConfig.java
> +                .allowedOrigins("http://localhost:8000", "http://localhost:3000")
넵 확인했습니다!

2024-01-09 13:52 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/AbstractTimeEntity.java
> +public abstract class AbstractTimeEntity {
앗 죄송합니다🤣 domain 에 있는 클래스만 남겨둘게요

넵 확인했습니다.

2024-01-09 14:00 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/config/JpaConfig.java
> +package org.devridge.api.config;
이 문제는 SpringBootApplication에 @EnableJpaAuditing를 추가하면 클래스를 따로 추가하지 않아도 괜찮을거에요!
저는 아래와 같이 사용했습니다.
```
package org.devridge.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;

@EnableJpaAuditing
@SpringBootApplication
public class DevridgeApiModuleApplication {

    public static void main(String[] args) {
        SpringApplication.run(DevridgeApiModuleApplication.class, args);
    }
}
```

2024-01-09 14:03 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/controller/MemberController.java
> +    @PostMapping("/one")
넵 공백 추가하겠습니다.
'/one' 이라고 썼던 건 1개 엔티티를 생성해서 그렇게 쓴거였습니다..!
생각해보니 REST API 엔드포인트에는 리소스를 식별할 수 있게 적는게 맞는 것 같네요 '/one'은 모두 삭제하겠습니다

2024-01-09 14:07 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    private String password;
PasswordChecker 클래스에서 비밀번호 검사하고 있어요. (5~16자)

구체적으로 정해지면 수정할 예정입니다!

2024-01-09 14:11 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    private String provider = MemberConstant.PROVIDER_NORMAL;
넵 확인했습니다!
member entity 에 추가할게요

2024-01-09 16:49 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/constant/SkillConstants.java
> +    static {
유저가 회원가입 시 입력한 직군 문자열을 검사한다는 말씀이신가요? 저도 말씀하신 대로 secret하게 관리해야 할 것 같다고 생각합니다. DB를 거치지 않고 검사하는게 낫다면,, 추후 캐시를 이용해 읽기 전용 DB에서 쿼리를 가져오는 방법도 있을 것 같습니다. 이 부분은 저도 잘 몰라서 같이 공부해보면 좋을 것 같아요!

2024-01-09 16:50 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/controller/MemberController.java
> +    @PostMapping("/one")
컨벤션 살펴보시면 명확하게 아실 수 있을 것 같아요 :)

2024-01-09 17:40 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +@NoArgsConstructor
`@NoArgsConstructor` 제거하고 직접 생성자 선언했습니다. (위 글 참조)

soft delete는 관련 개념 학습후에 추가하겠습니다. ㅠㅠ

2024-01-09 17:43 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +    @Column(name = "id", nullable = false)
PK 인 경우, 즉 `@Id` 어노테이션이 붙은 필드에 한해서는 고민해보겠습니다!

2024-01-09 17:43 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +    @Column(name = "password", nullable = false)
확인했습니다.

2024-01-09 18:24 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/repository/RefreshTokenRepository.java
> +    @Query("select rf FROM RefreshToken rf WHERE rf.member.id = :memberId")
해당 JPQL `rf` -> `token` 으로 단어 변경했습니다!

2024-01-09 18:25 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    private final MemberRepository memberRepository;
넵! 수정했습니다.

2024-01-09 18:30 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    @Transactional
현재 `createMember()` 메서드에서는 멤버를 생성하고, 스킬을 생성합니다.
그래서 2개의 작업을 하나의 트랜잭션으로 묶어야 한다고 생각했습니다. (멤버가 생성되면 멤버 직군도 같이 생성돼야 함)
하나라도 실패하면 롤백 되게끔요..! 어떻게 생각하시나요?

2024-01-09 18:31 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        if(!areSkillsValid(reqDto.getSkills())){
코드 컨벤션 좀 지켜야 겠네요...🥹

2024-01-09 18:32 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    public void createMemberSkill(CreateMemberRequest reqDto, Member member) {
넵 알겠습니다.

2024-01-09 18:34 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        for (String userSkill : userSkills) {
넵 확인했습니다!
Bulk 연산으로 SQL 쿼리 최적화 하겠습니다.

2024-01-09 18:35 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        for (String userSkill : userSkills) {
네 createMemberSkill() 이부분은 나중에 재정의 해야될 것 같네요.

프론트단에서 미리 서버에 모든 직군에 대한 이름과, 해당 id를 저장한 상태인 거죠?

2024-01-09 18:37 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        if (passwordEncoder.matches(reqDto.getPassword(), member.getPassword())){
네 그게 더 깔끔할 것 같네요! 조언 감사합니다.
그렇게 바꾸겠습니다~!

2024-01-09 18:39 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/PasswordChecker.java
> +        }
코드 컨벤션 잘 지키도록 노력하겠습니다!

2024-01-09 18:40 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/skill/dto/request/CreateMemberSkillRequest.java
> +package org.devridge.api.domain.skill.dto.request;
Skill 도메인 요청 dto, 응답 dto 클래스 삭제하겠습니다.

2024-01-09 18:41 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/MemberSkill.java
> +    @ManyToOne
네 모든 연관관계 매핑 지연 로딩으로 설정할게요! 감사합니다.

2024-01-09 18:42 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/MemberSkill.java
> +    private boolean isDeleted;
맞네요🤣 수정하겠습니다.

2024-01-09 18:47 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/exception/member/SkillsNotValidException.java
> +@Getter
없지요..ㅎㅎ
수정하겠습니다🤣

2024-01-09 18:47 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/security/auth/CustomMemberDetails.java
> +@Getter
아이고.. 넵 수정하겠습니다!!

2024-01-09 18:52 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/security/filter/JwtAuthenticationFilter.java
> +public class JwtAuthenticationFilter extends UsernamePasswordAuthenticationFilter {
코드 컨벤션대로 수정하겠습니다!

2024-01-09 18:58 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/security/filter/JwtAuthorizationFilter.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException, UserPrincipalNotFoundException {
메서드가 많이 길다는 것은 동의해요.
이미 3개 정도 메서드를 추출(extracted)한 상태이구요.

보시면 doFilter()를 호출하는 부분이 많은데, 해당 부분은 `doFilterInternal()` 호출하는게 흐름상 어색하지 않은 것 같아서요!
여기서 더 나누게 되면 메서드가 filterchain을 인자로 받게 되는데, 그렇게 되면 인자가 너무 많아져서 옳은 일일지 모르겠습니다.

혹시 좋은 방법 있으실까요...? 흠

2024-01-09 19:03 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/security/filter/JwtAuthorizationFilter.java
> +            return true;
![스크린샷 2024-01-10 오전 4 01 40](https://github.com/devridge-team-project/devridge-server/assets/56336436/fbf034a6-f26e-4dd6-99c2-dd73b6e40dfe)

보면 인자가 5개라서 메서드 따로 빼는게 맞지 않은 걸 수도 있거든요... (시큐리티 너무 어렵네요)
각 catch 마다 `return true`를 수행하는 로직이 들어가야 해서 현재로서는 떠오르는게 없네요

2024-01-09 19:04 UTC, Jungsu-lilly reviewed
리뷰 1차적으로 전부 달았습니다 (: 
성심성의껏 리뷰 주셔서 정말 감사합니다

2024-01-10 05:30 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    private String skills;
프론트에서 값을 어떻게 넘겨줄지 이 부분은 프론트 분들과 따로 얘기해봐야 할 것 같아요!
1차적으로 스킬들을 저장할 때 Backend -> Frontend로 넘겨주기 때문에 Frontend에 해당 스킬들의 id가 저장되고, 다시 Frontend -> Backend로 넘겨줄 때 해당 스킬들의 id를 유저의 스킬로 저장하면 된다고 생각했습니다.

추가적으로 split으로 넘겨줄 경우 공백 없이 `"react,javascript,python"`이런 식으로 넘겨줘야할 것 같네요!

2024-01-10 05:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    public String[] getSkills(){
Java Dto에 대해 찾아보시면, Dto는 로직을 가지지 않는 POJO 객체임을 아실 수 있을겁니다!
https://velog.io/@leesomyoung/Java-DAO-DTO-VO%EC%9D%98-%EA%B0%9C%EB%85%90

2024-01-10 05:32 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +@AllArgsConstructor
이 문제는 클래스가 아닌 생성자에 @Builder를 붙이시면 해결하실 수 있습니다.
```
package com.travity.api.domain.chatting.entity;

import com.travity.api.config.BaseTimeEntity;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.SQLDelete;

import javax.persistence.*;

import javax.validation.constraints.NotBlank;

@Getter
@Entity
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table(name = "chat_message")
@DynamicInsert
@SQLDelete(sql = "UPDATE chat_message SET is_deleted = true WHERE id = ?")
public class ChatMessage extends BaseTimeEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "member_id", nullable = false)
    private Long memberId;

    @Column(name = "chat_room_id", nullable = false)
    private Long chatRoomId;

    @NotBlank
    private String message;

    @Column(name = "message_type", nullable = false)
    private String messageType;

    @Column(name = "is_deleted")
    @ColumnDefault("false")
    private Boolean isDeleted;

    @Builder
    public ChatMessage(Long memberId, Long chatRoomId, String message, String messageType) {
        this.memberId = memberId;
        this.chatRoomId = chatRoomId;
        this.message = message;
        this.messageType = messageType;
    }
}
```

2024-01-10 05:33 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +@NoArgsConstructor
soft delete는 저희가 이전에 합의한대로 is_deleted를 true로 바꾸는 것이라 어렵지 않습니다!

2024-01-10 05:46 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    @Transactional
아하 두 작업을 UPDATE 하는군요 그렇다면 쓰는 것이 맞네요!

2024-01-10 05:46 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    public void createMemberSkill(CreateMemberRequest reqDto, Member member) {
해당 메소드를 사용하는 상위 메소드에서 Transaction을 하고 있으니 중복으로 추가하지 않아도 될 것 같은데 어떻게 생각하시나요!

2024-01-10 05:46 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        for (String userSkill : userSkills) {
위에서 언급드린대로 프론트 분들과 이야기 나누셔야 할 것 같습니다!

2024-01-10 05:46 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/MemberSkill.java
> +    private boolean isDeleted;
자동 변환된단 자료를 못 찾고 있는데 혹시 관련 자료를 받을 수 있을까요? 🥹
https://velog.io/@duridudu/TIL-JPA-%EC%82%BD%EC%A7%88-%EC%A0%95%EB%A6%AC
저는 바꿔줘야 한다는 글을 보고 수동으로 바꾸긴 했습니다..!

2024-01-10 05:46 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/config/SecurityConfig.java
> +        AuthenticationManager authenticationManager = authenticationManager(http.getSharedObject(AuthenticationConfiguration.class));
최고예요!

2024-01-10 05:46 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/util/JwtUtil.java
> +    private static long TOKEN_VALIDITY_TIME_IN_SECONDS = 1000;
유틸리티 클래스를 정적으로 선언하신 이유가 궁금하네요..!
그리고 정적으로 만든다면 이 역시 컴포넌트 스캔은 하지 않아도 될 것 같아요!

2024-01-10 05:46 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/util/JwtUtil.java
> +    private static Map<String, Object> createAccessTokenClaims(Member member, Long refreshTokenId) {
Map보다는 dto가 조금 더 데이터 형태가 명확하고 코드 가독성이 좋다고 생각했습니다.
아래 Map 자체를 하드 코딩 하는게 사실 괜찮은지 확신이 서지 않네요 ㅠ_ㅠ
JWT 내에서는 map을 무조건 사용해야 하나요?

2024-01-10 08:23 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    private String provider = MemberConstant.PROVIDER_NORMAL;
그렇다면 프론트엔드 자체적으로 저 값을 기본으로 넘겨주는 것은 어떤가요? Dto에 기본 값이 있는게 좋은 코드는 아닌 것 같네요..!

2024-01-10 09:39 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/util/JwtUtil.java
> +    private static long TOKEN_VALIDITY_TIME_IN_SECONDS = 1000;
JwtUtil 은 `JwtAuthenticationFilter`, `JwtAuthorizationFilter` 클래스에서 사용해요.

![스크린샷 2024-01-10 오후 6 37 44](https://github.com/devridge-team-project/devridge-server/assets/56336436/165405bc-1e7a-4d77-8f03-fa14c564d616)
![스크린샷 2024-01-10 오후 6 38 16](https://github.com/devridge-team-project/devridge-server/assets/56336436/283180b6-b2bb-4172-894d-7b76d4d18a09)

이처럼 사용성 측면에서 정적으로 만들었던 거였습니다...!
@Component는 없어도 될 거 같아요. 빼겠습니다🥹

2024-01-10 09:45 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/util/JwtUtil.java
> +    private static Map<String, Object> createAccessTokenClaims(Member member, Long refreshTokenId) {
![스크린샷 2024-01-10 오후 6 44 39](https://github.com/devridge-team-project/devridge-server/assets/56336436/6c454aa1-037e-4446-93ee-00ffa3e726a2)

현재 사용하는 Jwts 에서는 setClaims() 에 Map을 넣어야한다고 되어있어요!
JWT 라이브러리는 클레임을 Map 형태로 요구하니까, 관행을 따라가는 것이 좋아보입니다.

2024-01-10 09:47 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/constant/SkillConstants.java
> +    static {
네 이부분은 트러블슈팅에 적어놓겠습니다.

2024-01-10 09:49 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    private String provider = MemberConstant.PROVIDER_NORMAL;
넵 provider를 요청받을 때, 전달받는 식으로 하겠습니다!

2024-01-10 09:54 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
> +    public String[] getSkills(){
dto에 로직을 넣지 않는게 맞겠네요. 서비스 단으로 옮기겠습니다!

2024-01-10 09:57 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +@NoArgsConstructor
넵 삭제 로직 soft delete 되게 수정하겠습니다!

2024-01-10 10:24 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    public void createMemberSkill(CreateMemberRequest reqDto, Member member) {
`createMember()` 에서 이미 트랜잭션을 하고 있으니 말하신대로 제거하겠습니다!

2024-01-10 10:34 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +@AllArgsConstructor
오... 그렇군요
생성자에 `@Builder` 추가하고, 클래스에서 제거하겠습니다~!

`@AllArgsConstructor`, `@NoArgsConstructor` 도 제거할게요.

2024-01-10 10:36 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        if (passwordEncoder.matches(reqDto.getPassword(), member.getPassword())){
수정했습니다!

2024-01-10 10:38 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/MemberSkill.java
> +    private boolean isDeleted;
![스크린샷 2024-01-10 오후 7 37 15](https://github.com/devridge-team-project/devridge-server/assets/56336436/3f8bd991-cabe-42e4-b492-42d926f7a4e5)

찾아보니, bit로 자동 변환된다고 되어있네요 🤣
`@ColumnDefinition`으로 명시적으로 정해주겠습니다.

2024-01-10 12:59 UTC, 213kky approved these changes
고생하셨습니다!

2024-01-10 17:23 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/constant/SkillConstants.java
> +    static {
우선은 DB에서 검사하는 것이 추후 확장성에도 좋을 것 같아요! (DB에 새로운 스킬셋이 추가된다면 추가적으로 코드를 수정해야하는 번거로움도 있을 것 같아요.)

2024-01-10 17:34 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +    protected Member() {
이 부분은 @NoArgs를 사용하시는 것도 좋아보입니다!

2024-01-10 17:34 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    public void createMemberSkill(CreateMemberRequest reqDto, Member member) {
private로 다른 레이어에서 쓰지 않는 코드는 캡슐화 해주세요~!

2024-01-10 17:37 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/filter/JwtAuthorizationFilter.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException, UserPrincipalNotFoundException {
일단은 이대로 진행하시고 추후 작업하시면서 리팩토링 하는 것도 좋을 것 같네요 🤔🤔

2024-01-10 17:38 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/constant/SkillConstants.java
> +    private SkillConstants() {
@NoArgs(access = AccessLevel.PRIVATE) 로 넣으시면 가독성에 조금 더 도움이 될 것 같아요!

2024-01-10 17:43 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/security/constant/SecurityConstant.java
> +public interface SecurityConstant {
이 부분은 전역적으로 사용하시나요?_?

2024-01-10 17:44 UTC, yu-heejin commented
1. build.gradle 충돌을 해결해주세요.
2. 아직 해결 안 된 부분이 있어서 수정 해주시고 말씀해주세요! 논의가 필요한 부분은 넘기시고 이슈로 발행해주세요.
3. print문이 조금 남아있어서 그 부분만 지워주시면 될 것 같아요 :)

2024-01-10 18:39 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/security/constant/SecurityConstant.java
> +public interface SecurityConstant {
![스크린샷 2024-01-11 오전 3 38 36](https://github.com/devridge-team-project/devridge-server/assets/56336436/0df159e4-26f6-458c-89c0-466357d2edc1)

다음과 같이 수정했습니다!

SucurituConfig 클래스에서 빈으로 주입받아 사용하는 것으로 바꿨습니다.

2024-01-10 18:40 UTC, Jungsu-lilly commented
모두 올렸습니다. 확인 부탁드립니다!

2024-01-10 18:46 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +    protected Member() {
원래 @NoArgsConstructor 를 사용했었다가, 빈 생성자를 사용하는 걸로 바꾸었습니다..ㅎㅎ

2024-01-10 18:52 UTC, Jungsu-lilly commented
리뷰 주신 내용들 대부분 반영하여 수정하였습니다 ☺️
해결 하지 못한 부분들은 나중에 따로 이슈 파서 남기도록 하겠습니다!

2024-01-11 08:07 UTC, yu-heejin approved these changes
수정 안된 부분은 나중에 제가 주석으로 달아드릴테니 우선은 머지 부탁드립니다.

2024-01-11 08:21 UTC, merged