Q&A CRUD API 기능을 구현합니다.
devridge-team-project/devridge-server pull request #20
Opened 2024-01-17 07:31 UTC by yu-heejin

## Description ✍️
* Q&A CRUD API 기능을 구현했습니다.
* 추후 조회수, 좋아요 등 심화 기능을 구현할 예정입니다.

## 테스트 시 유의사항 ⚠️
* API 명세서에 작성 후 슬랙에 알림 드리겠습니다.

## Merge 전 체크 리스트 ✅
- [ ] Backend 컨벤션을 잘 지켰나요?
- [ ] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

2024-01-17 12:23 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/qna/service/QnAService.java
> +        QnA result = this.checkQnAValidate(qnaId);
Exception을 throw 하는 부분을 따로 메서드로 나누신 이유가 있을까요? 궁금해서 여쭤봅니다.

2024-01-17 12:33 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/QnA.java
> +    private Long memberId;
3-comment-api 브랜치에서 진행중입니다 :)

2024-01-17 12:35 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/CommentLikeDislike.java
> +    private Boolean isDeleted;
저도 동의합니다 이부분은 수정하겠습니다!

2024-01-17 12:35 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/key/CommentLikeDislikeKey.java
> +public class CommentLikeDislikeKey implements Serializable {
Id 라는 이름이 더 직관적이고 보기 좋은 것 같네요. 이부분도 수정하겠습니다 :)

2024-01-17 12:36 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/QnAComment.java
> +    @JsonBackReference
ㅠ_ㅠ 근데 코드 너무 지저분해지는 것 같아서 다른 방법을 고안중입니다,,,

2024-01-17 12:46 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/QnAComment.java
> +    @JsonBackReference
저도 이부분 좀더 조사해서 오겠습니다.. 흠

2024-01-17 16:42 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/qna/controller/QnAController.java
> +        return ResponseEntity.created(URI.create("/api/qna/" + qnaId)).build();
Status : 201(Created)을 반환하는데, 모든 요청에 대해 성공하면, 200으로 통일하는 것은 어떤가요?

2024-01-17 19:23 UTC, 213kky requested changes
확인하였습니다.

2024-01-17 19:23 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/QnA.java
> +        this.memberId = 1L;
merge 전에 수정하셔야 할 것 같습니다.

2024-01-17 19:23 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/qna/service/QnAService.java
> +        if (sortOption.equals("views")) return qnaQuerydslRepository.findAllQnASortByViews();
중괄호를 생략하지 않는 건 어떻게 생각하시나요? 구글 코딩 컨벤션에서는 코드가 없거나 단 하나라도 중괄호를 생략하지 않는다고 합니다.

2024-01-17 19:23 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/QnA.java
> +    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "qna")
@OneToMany에 fetch = FetchType.LAZY를 명시적으로 작성하는 이유가 있나요?

2024-01-18 03:42 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/qna/controller/QnAController.java
> +        return ResponseEntity.created(URI.create("/api/qna/" + qnaId)).build();
혹시 200으로 통일하고 싶으신 이유가 있으실까요?
![E63FA07A-1350-4994-8288-CDDD04196197](https://github.com/devridge-team-project/devridge-server/assets/96467030/753ef9b1-1b99-407d-a3ec-1371e4c0ab95)

2024-01-18 03:44 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/QnA.java
> +        this.memberId = 1L;
저 부분은 하위 브랜치에서 진행중입니다!

2024-01-18 03:44 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/qna/service/QnAService.java
> +        if (sortOption.equals("views")) return qnaQuerydslRepository.findAllQnASortByViews();
네 이부분은 수정하겠습니다~

2024-01-18 03:47 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/QnA.java
> +    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "qna")
명시하지 않으면 즉시 로딩 됩니다. QnA 목록을 보여주는 경우에는 댓글이 필요 없기 때문입니다. 즉시 로딩 된다면 댓글이 필요 없는 상황에서도 댓글을 불러오기 때문에 비효율적인 쿼리로 요청하게 됩니다.
https://imucoding.tistory.com/m/235

2024-01-18 04:54 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/qna/entity/QnA.java
> +    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "qna")
@ManyToOne와 다르게 @OneToMany는 기본값이 FetchType.LAZY라고합니다.
https://velog.io/@yuseogi0218/JPA-%EC%A6%89%EC%8B%9C%EB%A1%9C%EB%94%A9%EA%B3%BC-%EC%A7%80%EC%97%B0%EB%A1%9C%EB%94%A9-FetchType.EAGER-or-LAZY

2024-01-18 05:17 UTC, 213kky approved these changes
확인했습니다.

2024-01-18 05:30 UTC, Jungsu-lilly approved these changes
확인했습니다~~! 수고하셨어요

2024-01-18 05:34 UTC, merged