Community API 기능을 구현합니다.
devridge-team-project/devridge-server pull request #23
Opened 2024-01-19 12:53 UTC by 213kky

## Description ✍️
* community 게시글 crud
* community 댓글 crud
* community 추천, 비추천
* community 스크랩

## Merge 전 체크 리스트 ✅
- [ ] Backend 컨벤션을 잘 지켰나요?
- [ ] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

closed #13

2024-01-19 13:40 UTC, yu-heejin requested changes
중복되는 리뷰는 따로 드리진 않았으나 보시고 다른 코드도 점검해보세요!
전반적으로 코드 스타일 더 신경써주시면 감사하겠습니다.
고생하셨어요.

2024-01-19 13:40 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityCommentController.java
> +    public ResponseEntity<?> writeComment(@Valid @RequestBody CommunityCommentRequest dto,
추가적으로 dto라는 이름은 사용하지 않는 것을 권장합니다. 이전에 정수님께 드렸던 코드 리뷰 참고해보세요.

2024-01-19 13:40 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityCommentLikeDislikeController.java
> +        String message;
추가적으로 궁금한 점이 status를 PathVariable로 받고 계신 이유가 있으신가요?

2024-01-19 13:40 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityCommentLikeDislikeService.java
> +            communityCommentLikeDislikeRepository.save(communityCommentLikeDislike);
이 부분은 GlobalException으로 잡아주세요!

2024-01-19 13:40 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityCommentLikeDislikeService.java
> +        communityCommentLikeDislike.ifPresentOrElse(
ifPresent를 사용하는 것 보단 orElseThrows를 사용하시는 편이 더 좋습니다.
https://medium.com/@hee98.09.14/java-optional-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EC%93%B0%EA%B8%B0-6e359e2259c6

2024-01-19 13:40 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityCommentService.java
> +        List<CommunityComment> communityComments =
이때는 NPE를 내는 것도 좋은데 그냥 빈 배열을 반환하는 편도 좋습니다.
https://sedangdang.tistory.com/247

2024-01-19 13:40 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityService.java
> +        if (!SecurityContextHolderUtil.getMemberId().equals(community.getMemberId())) {
중복되는 로직은 util로 따로 빼도 괜찮을 것 같아요~

2024-01-19 13:40 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityService.java
> +    public List<Community> viewAllCommunity() {
이 부분 아마 responseDto 없이 반환하면 Member의 모든 민감 정보가 나올 것 같은데 맞나요?

2024-01-19 13:40 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
> +    @OneToMany(mappedBy = "member")
굳이 모든 엔티티에 양방향을 하실 필요는 없습니다...!!! 양방향 매핑은 신중하게 하셔야해요.

2024-01-19 17:11 UTC, Jungsu-lilly requested changes
코드 스타일 좀더 신경써주시면 좋을 것 같아요!
수고 많으셨습니다~!

2024-01-19 17:11 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/communityscrap/CommunityScrapController.java
> +    public ResponseEntity<?> scrapdelete(@PathVariable Long memberId,
서비스단에서는 `deleteScrap` 이라고 네이밍 하셨는데, 컨트롤러 단에서 변경을 준 이유가 궁금합니다.

2024-01-19 17:34 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityCommentController.java
> +@RequestMapping("/api/community/comment")
이 부분이 커뮤니티 댓글 부분이라 커뮤니티 아이디가 꼭 필요합니다!

2024-01-24 15:50 UTC, yu-heejin approved these changes
고생하셨습니다~

2024-01-24 15:50 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityCommentController.java
> +@RequestMapping("/api/community/{communityId}/comment")
이 부분은 나중에 복수형으로 수정해주세요~

2024-01-24 17:04 UTC, Jungsu-lilly approved these changes
수고하셨습니다!

2024-01-25 06:10 UTC, merged

2024-01-28 02:38 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityCommentService.java
> +        List<CommunityComment> communityComments =
값이 없으면 일반적으로 빈 배열을 반환하지 않나요? 단일 객체만 Optional을 사용하는 것으로 알고있는데..!