로그인 관련 로직을 수정, 개선하였습니다.
devridge-team-project/devridge-server pull request #24
Opened 2024-01-21 17:33 UTC by Jungsu-lilly

## Description ✍️
* 피드백 받은 것을 바탕으로, 유저 로그인 개선 및 수정 작업을 진행했습니다.
* 회원 가입 시 스킬셋을 id로 넘겨주는 로직 추가
* 회원 가입 => MemberSkill 테이블 생성 시, DB 방문 횟수를 줄였습니다.

## 테스트 시 유의사항 ⚠️
* 현재 테스트 시, 모든 경로에 대하여 인증이 필요합니다. 
* 이는 추후 인증이 필요없는 경로에 대해, 인증을 제거할 것입니다.

## Merge 전 체크 리스트 ✅
- [ ] Backend 컨벤션을 잘 지켰나요?
- [ ] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

2024-01-21 18:05 UTC, yu-heejin requested changes

2024-01-21 18:05 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        List<Long> skillIds = memberRequest.getSkillIds();
문자열로 들어오는 새로운 스킬들에 대한 처리는 나중에 따로 추가해주실건가요?

2024-01-21 18:16 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +    public List<Skill> areSkillsValid(List<Long> skillIds) {
우선 로그인을 하기 전에, 어떤 스킬들이 있는지 DB에서 스킬셋 전체를 받아오는 작업이 필요해요!

1. 회원 가입 전에 `GET /api/skills` 를 호출해 서버의 {id, skillName}을 모두 불러옵니다. -> 이는 프런트에서 저장해놓으면 될듯!
2. 회원 가입 시 skillIds = [1, 2, 4, 5] 식으로 요청 바디로 보내면, 그 id 값들이 서버에 존재하는지(유효한지), 확인하는 거에요!

포스트맨에 예시를 적어두었습니다.

2024-01-21 18:17 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/MemberSkill.java
> +    @Column(name = "is_deleted", columnDefinition = "TINYINT(1)")
모든 엔티티 수정해서 올리도록 하겠습니다😂

2024-01-21 18:17 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/security/filter/JwtAuthenticationFilter.java
> +            HttpStatus.OK.value(),
넵 지금 수정해서 올리는 중입니다!

2024-01-21 18:21 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/security/config/SecurityConfig.java
> +        JwtAuthenticationFilter authenticationFilter = new JwtAuthenticationFilter(refreshTokenRepository, new TokenResponse());
아니요 없습니다.

<img width="809" alt="스크린샷 2024-01-22 오전 3 20 24" src="https://github.com/devridge-team-project/devridge-server/assets/56336436/3e23bcb4-4a28-4eea-9e1c-94684a24fb04">

현재 다음과 같이 사용을 하는데, 주입받을 필요가 없겠네요...!
TokenResponse 받지 않도록 수정하겠습니다.

2024-01-21 18:23 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
> +        List<Long> skillIds = memberRequest.getSkillIds();
저도 그렇게 생각했는데, 설계서 보시면 유저가 커스텀하게 스킬셋을 추가할 수 있는 부분이 없는 것 같더라구요.
확인해보시겠어요?

2024-01-23 15:58 UTC, 213kky approved these changes
확인했습니다.

2024-01-23 15:58 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/Skill.java
>      private Set<MemberSkill> memberSkills = new HashSet<>();
이거 안쓰시는거 같습니다.

2024-01-23 18:02 UTC, yu-heejin approved these changes
고생하셨습니다~

2024-01-24 01:22 UTC, merged

2024-01-24 01:26 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/repository/MemberRepository.java
>      public Optional<Member> findByEmail(String email);
아 이메일 관련해서 들어갔네요🤣
추후 이메일 인증 관련해서는 쓰인다고 알아주시면 될 것 같습니다.

2024-01-24 01:32 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/Skill.java
>      private Set<MemberSkill> memberSkills = new HashSet<>();
그 부분은 추후에 쓸수도 있어서 남겨놓겠습니다.

2024-01-24 01:53 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/member/entity/RefreshToken.java
>  public class RefreshToken extends AbstractTimeEntity {
일단 RefreshToken은 is_deleted 필드가 없어야 해요. (현재 로직 상)
그래서 바로 삭제하는 로직으로, 일단 그대로 두겠습니다.