커뮤니티 게시글, 댓글, 추천/비추천, 스크랩 리팩토링 및 해시태그 기능추가
devridge-team-project/devridge-server pull request #49
Opened 2024-02-05 12:02 UTC by 213kky

## Description ✍️
* 게시글, 댓글, 추천/비추천, 스크랩 코드 리팩토링하였습니다.
* 해시태그 기능 구현하였습니다.

## 테스트 시 유의사항 ⚠️
* postman에 반영하였습니다.

## Merge 전 체크 리스트 ✅
- [ ] Backend 컨벤션을 잘 지켰나요?
- [ ] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

2024-02-05 12:27 UTC, yu-heejin requested changes
@ColumnDefault랑 CommunityHashTagsRepository에 id명 오타 때문에 RC 드렸습니다! 고생하셨어요

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityController.java
> +        communityService.updateCommunityAndHashtag(communityId, communityRequest);
궁금한게 해시태그도 수정 가능한가요? 해시태그 테이블안에 저장하고 참조하는 방식으로 알고 있어서요..!

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityCommentLikeDislikeController.java
> +        ) {
```suggestion
     ) {
```

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityHashtagController.java
> +    @GetMapping("/api/hashtags/{hashtagId}")
따로 만드시는거면 해시태그가 프론트에서 추가될 때마다 API 요청이 이루어지는건가요?

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/dto/request/hashtagRequest.java
> +    private List<String> hashtags;
createCommunity에도 해시태그가 있고 여기도 해시태그가 있군요..?

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityCommentResponse.java
> +    private Long id;
comment 반환하실 때 memberId도 반환하셔야 어떤 멤버가 쓴 댓글인지 명확하게 알 수 있을 것 같아요!

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityListResponse.java
> +    private Long likeCount;
여기 dislike는 따로 없는거죠?

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Community.java
> +    @OneToMany(mappedBy = "community")
댓글도 cascade가 필요할 것 같아요!

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Hashtag.java
> +    @OneToMany(mappedBy = "hashtag", cascade = CascadeType.ALL, orphanRemoval = true/*, fetch = FetchType.EAGER*/)
HashTags에 OneToMany를 거신 이유가 있을까요? 따로 불러올 일이 없을 것 같아서요!

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Hashtag.java
> +    private Long count;
`@ColumnDefault`가 빠진 것 같네요

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/mapper/CommunityCommentMapper.java
> +    public CommunityCommentResponse toCommentResponse(CommunityComment comment) {
추후 탈퇴한 사용자에 대한 처리도 해주시면 좋습니다!

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/repository/CommunityHashtagRepository.java
> +    List<CommunityHashtag> findAllByCommunityId(Long communityID);
```suggestion
    List<CommunityHashtag> findAllByCommunityId(Long communityId);
```

2024-02-05 12:27 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityHashtagService.java
> +        List<CommunityHashtag> communityHashtags = communityHashtagRepository.findAllByHashtagId(hashtagId);
hashtagId로 커뮤니티의 모든 해시태그를 찾는건가요?! 커뮤니티의 아이디로 모든 해시태그를 찾는 것이라 생각해서 여쭤봅니다.

2024-02-05 12:29 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/dto/request/hashtagRequest.java
> +    private List<String> hashtags;
이 부분은 삭제해야하는데 놓쳤네요

2024-02-05 12:33 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityListResponse.java
> +    private Long likeCount;
아직 커뮤니티 화면이 나온건 아니라 확정은 아니겠지만 qna 게시글 목록 기준으로는 추천수만 화면에 보이길래 이렇게 해놨습니다.

2024-02-05 12:40 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityHashtagService.java
> +        List<CommunityHashtag> communityHashtags = communityHashtagRepository.findAllByHashtagId(hashtagId);
해시태그를 클릭해서 해시태그id를 이용해 해당 해시태그를 갖는 모든 커뮤니티글을 찾으려는 의도로 작성한 부분입니다.

2024-02-05 12:47 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityController.java
> +        communityService.updateCommunityAndHashtag(communityId, communityRequest);
해시태그 자체는 수정을 하지는 않고 중간 테이블에서 커뮤니티id랑 hashtagid로 연결을 변경하는 방식으로 수정,삭제를 합니다.

2024-02-05 12:48 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityHashtagController.java
> +    @GetMapping("/api/hashtags/{hashtagId}")
이 부분은 해시태그를 누를 때 발생하는 요청으로 해당 해시태그를 지닌 커뮤니티를 부르는 역할입니다.

2024-02-05 13:05 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Hashtag.java
> +    private Long count;
DB에서 기본값 설정을 하기 때문에 문제 없다고 생각하는데 명시적으로 작성하는 이유가 있나요??

2024-02-05 13:10 UTC, Jungsu-lilly reviewed
수고하셨습니다~! 질문 관련 코멘트 답해주시면 감사하겠습니다.

2024-02-05 13:10 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Hashtag.java
> +    private String word;
`@NotNull` 붙여주셔도 좋을 것 같습니다.

2024-02-05 13:37 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Hashtag.java
> +    private Long count;
이 부분이 아마 없으면 오류나는 걸로 알고 있습니다~!
https://eocoding.tistory.com/71

2024-02-05 13:37 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Hashtag.java
> +    @OneToMany(mappedBy = "hashtag", cascade = CascadeType.ALL, orphanRemoval = true/*, fetch = FetchType.EAGER*/)
HashtagRepository에서 jpql으로 사용을 합니다!
![image](https://github.com/devridge-team-project/devridge-server/assets/108410827/139affac-3d14-4db1-94bd-0c955fd8044e)

2024-02-05 14:09 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/CommunityScrap.java
> -@Where(clause = "is_deleted = false")
지워진 부분은 is_deleted = false인 부분만 jpa가 처리하도록 하는 부분을 삭제했습니다!
논리삭제는 사용중이에요

2024-02-05 14:20 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/service/CommunityHashtagService.java
> +                    communityHashtagRepository.save(new CommunityHashtag(community, hashtag));
마지막 커밋은 코드 살짝 수정이 있는데 어느 부분을 말씀하시는건지 알  수 있을까요?

2024-02-06 05:06 UTC, yu-heejin approved these changes
:)

2024-02-06 05:06 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityController.java
> +        communityService.updateCommunityAndHashtag(communityId, communityRequest);
해시태그 삭제랑 추가가 update라고 이해하면 될까요?-?

2024-02-06 06:05 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityController.java
> +        communityService.updateCommunityAndHashtag(communityId, communityRequest);
updateCommunityAndHashtag는 기존에 연결된 해시태그를 삭제하고 새로 연결하는 수정을 담당한다고 생각하시면 될것 같아요. 

순수한 삭제는 communityService에 deleteCommunity가 삭제를 담당합니다.

메소드 네이밍을 조금 수정해야겠네요

2024-02-06 06:08 UTC, merged