74 community study api
devridge-team-project/devridge-server pull request #75
Opened 2024-02-23 08:46 UTC by 213kky

## Description ✍️
* 커뮤니티 스터디 crud를 구현하였습니다.
* 프로젝트 디자인이 완성되지 않아 추후 변경 사항 반영할 예정입니다.

## 테스트 시 유의사항 ⚠️
* postman에 올려두었습니다.

## Merge 전 체크 리스트 ✅
- [ ] Backend 컨벤션을 잘 지켰나요?
- [ ] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

2024-02-23 10:25 UTC, Jungsu-lilly requested changes
수정사항, 질문사항 요청드렸습니다! 
수고하셨습니다~~

2024-02-23 10:25 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Study.java
> +    private Long views;
:question: 스터디에도 좋아요/싫어요, 조회수가 있나요?

2024-02-23 10:25 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/community/mapper/StudyMapper.java
> +            return Study.builder()
:pill: builder가 중복되는데, 리팩토링 하면 좋을 것 같습니다.

2024-02-23 10:25 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/community/mapper/StudyMapper.java
> +        if (studyRequest.getImages() != null && !studyRequest.getImages().isEmpty()) {
:question: 조건식에서 이 두가지를 확인하는 이유가 있을까요?
`getImage() != null` 을 먼저 확인하는 이유가 궁금합니다.

2024-02-23 10:25 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/community/controller/StudyController.java
> +        List<StudyListResponse> studyListResponses = studyService.getAllStudy();
:pill: `getAll()` 아니면 `getAllStudies()` 명명하면 좋을 것 같습니다!

2024-02-23 10:49 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Study.java
> +    private Long views;
아직 결정된 것이 없긴 하지만 좋아요나 조회수 부분은 일반적으로 있는 경우가 많다고 생각해서 넣어놨습니다.

2024-02-23 10:51 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/mapper/StudyMapper.java
> +        if (studyRequest.getImages() != null && !studyRequest.getImages().isEmpty()) {
getImage() != null 확인없이 isempty하면 NPE 발생해요

2024-02-23 10:55 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/mapper/StudyMapper.java
> +            return Study.builder()
25번라인 말하시는걸까요?

2024-02-23 11:00 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/controller/StudyController.java
> +        List<StudyListResponse> studyListResponses = studyService.getAllStudy();
All이라는 부분에서 복수표현을 했는데 뒤에 또 복수를 사용하는것보다는 study가 맞지 않나요??

2024-02-23 11:04 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Study.java
> +    @ColumnDefault("0")
생각해보긴 했었는데 방법이 다양해서 작성자가 임의로 게시글에 맴버를 추가해야 하는지, 승인을 받는다든지 등 구체적으로 나와야 할 수 있는 부분인 것 같아요 화면 상세보기도 안나와있어서...

2024-02-23 16:36 UTC, yu-heejin approved these changes

2024-02-24 01:56 UTC, Jungsu-lilly commented on api-module/src/main/java/org/devridge/api/domain/community/mapper/StudyMapper.java
> +            return Study.builder()
넵 전반적으로요!

2024-02-24 02:01 UTC, Jungsu-lilly approved these changes
수고하셨습니다~~!

2024-02-24 08:07 UTC, merged