무한스크롤 구현 및 화면 변경에 따른 Community API 수정 및 리팩토링합니다.
devridge-team-project/devridge-server pull request #79
Opened 2024-02-27 13:46 UTC by 213kky

## Description ✍️
* 자유게시판 전체 목록 무한스크롤을 구현하였습니다.
* 자유게시글 댓글 목록 무한스크롤을 구현하였습니다.
* 프로젝트 전체 목록 무한스크롤을 구현하였습니다.
* 화면 디자인에 맞게 api를 수정하였습니다.

## 테스트 시 유의사항 ⚠️
* postman에서 테스트 가능합니다.

## Merge 전 체크 리스트 ✅
- [ ] Backend 컨벤션을 잘 지켰나요?
- [ ] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

2024-02-28 15:31 UTC, yu-heejin requested changes
몇가지 수정사항 있어서 RC 드립니다! 고생하셨어요!

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityCommentController.java
> +//    @GetMapping
❗️ 이 부분은 필요 없는 코드라면 삭제 부탁드립니다!

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/controller/CommunityController.java
> +//    @GetMapping
❗️ 여기도 확인해주세요~!

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/dto/request/ProjectRequest.java
> +    private Meeting meeting;
💊 이 부분 나중에 enumValidator 하나 만들어주시면 좋습니다.

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityListResponse.java
> +    private Long comments;
💊 comments라고 이름을 바꾸신 이유가 있으신가요? 댓글의 개수를 저장하는 변수라면 기존 이름이 더 직관적인 것 같아요.

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/HashtagResponse.java
> +@NoArgsConstructor
❓ NoArgs는 없어도 괜찮지 않나요?

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/ProjectDetailResponse.java
> +    private String category;
💊 위에 필드랑 코드 스타일(여백) 통일해주시면 좋을 것 같습니다~ 다른 부분도 마찬가지!

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Meeting.java
> +public enum Meeting {
❓ 특별히 한글로 하신 이유가 있으신가요? online, offline으로 해도 괜찮을지도..?

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Community.java
> +    @OneToMany(mappedBy = "community", cascade = CascadeType.ALL)
❓ 해당 필드에 cascade 타입을 ALL로 설정하신 이유가 있으신가요?
추가적으로 위에 해시태그의 경우 cascade를 All로 설정하시면 해당 커뮤니티 글이 삭제될 때 모든 해시태그가 삭제되어 위험할 것 같습니다..!

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/repository/CommunityQuerydslRepository.java
> +        while (results.size() <= 10) {
❓ 궁금한 점이 여기서 while문을 돌리시는 이유가 있으신가요? 아래 코드를 보면 List로 받아오는 것 같아서요

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/ProjectService.java
> +        for (ProjectSkill t : temp) {
💊 temp라는 이름 보다는 명확한 이름을 써 주시면 좋을 것 같네요
```suggestion
        for (ProjectSkill skill : project.getProjectSkills()) {
```

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/ProjectService.java
> +        project.updateProject(
💊 해당 부분 Builder로 처리하시면 null 필드를 추가하지 않아도 괜찮을거에요!
한 엔티티에 @Builder를 두개 사용할 수 없다면 클래스 단에 추가해주시면 됩니다.

2024-02-28 15:31 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/ProjectService.java
> +            projectSkillRepository.save(
💊 save를 반복문으로 저장하시면 N + 1 이슈 발생할거에요! bulk insert나 saveAll 사용해주세요.

2024-02-29 07:15 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityListResponse.java
> +    private Long comments;
comments가 간결해서 이렇게 작성했는데 다시 수정할게요

2024-02-29 07:20 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/HashtagResponse.java
> +@NoArgsConstructor
없으면 에러가 뜨더라고요...

2024-02-29 07:21 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Meeting.java
> +public enum Meeting {
화면설계에 한글로 되어있어서 이렇게 했어요

2024-02-29 07:24 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/ProjectDetailResponse.java
> +    private String category;
어노테이션 붙은것들 다 붙이면 가독성이 안 좋지 않을까요?

2024-02-29 07:29 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/repository/CommunityQuerydslRepository.java
> +        while (results.size() <= 10) {
List로 받아오는데 이게 ResponseList안에 List가 존재하면 
{
"id": 1 ,
"hashtag": ["a", "b"]
}

이렇게 받아와서 1개여야하는데 

{
"id": 1 ,
"hashtag": [ "a"]
}

{
"id": 1 ,
"hashtag": [ "b"]
}

반환이 이렇게 2개가 되어 중복을 제거하는 과정에서 
limit가 10개여도 반환할게 한개뿐일 경우가 있어서 최소 반환 갯수를 위해서 이렇게 작성했어요

2024-02-29 07:43 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/service/ProjectService.java
> +        project.updateProject(
제가 잘못 이해한걸수도 있는데 해당 부분은 업데이트 하는 부분으로 DB에서 객체 조회해서 값을 변경하고 Dirty Checking을 이용한 부분이라  Builder를 사용할 수 없는 부분아닐까요?

2024-02-29 07:49 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Community.java
> +    @OneToMany(mappedBy = "community", cascade = CascadeType.ALL)
커뮤니티 글이 삭제되면 스크랩도 같이 삭제해야하지 않나요??
해시태그의 경우도 게시글이 해시태그가 같이 삭제되는게 맞다고 생각하고 중간의 매핑테이블만 영향받아서 괜찮다고 생각합니다.

2024-02-29 08:18 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/service/ProjectService.java
> +            projectSkillRepository.save(
IDENTITY전략을 써서 bulk insert사용이 안된다고 하네요 다른 방법을 찾아볼게요

2024-02-29 09:59 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/dto/response/ProjectDetailResponse.java
> +    private String category;
아래 필드에 공백을 추가해주세요~

2024-02-29 10:00 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Community.java
> +    @OneToMany(mappedBy = "community", cascade = CascadeType.ALL)
커뮤니티 해시태그는 다른 게시물에서 재사용하지 않나요?

2024-02-29 10:02 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/ProjectService.java
> +        project.updateProject(
아뇨 전 엔티티에 추가해달라는 말씀이었습니다~!

2024-02-29 10:06 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/repository/CommunityQuerydslRepository.java
> +        while (results.size() <= 10) {
왜 반환 값이 저렇게 나오나요..? 그리고 아마 limit가 10개일 때 반환할 경우가 한개인 경우엔 그냥 한개만 나오지 않나요?

2024-02-29 10:26 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Community.java
> +    @OneToMany(mappedBy = "community", cascade = CascadeType.ALL)
아 처음 설계상 다른곳에서도 쓰려고 계획되어있긴했네요 
저는 자유게시판에서만 쓰는 걸로 알고있었는데 
다른 게시물에서 태그기능을 사용하더라도 중간테이블 따로 만들어야 해서 상관없을것같아요

2024-02-29 10:59 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/service/ProjectService.java
> +        project.updateProject(
생성자에는 Builder붙여서 사용중이고
이 부분은 도메인에서 만든 메소드인데 Builder랑 무슨관련인지 이해를 못했어요...ㅜㅜ

2024-02-29 11:03 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/service/ProjectService.java
> +        project.updateProject(
null 값을 하드코딩 하고 계셔서 빌더를 쓰면 null을 넣지 않아도 괜찮을 것 같다는 말씀이었는데 생각해보니 빌더는 생성자에 붙이는 메소드네요,,, 그냥 넘기셔도 될 것 같습니다..,,!

2024-02-29 11:09 UTC, Jungsu-lilly approved these changes
수고하셨습니다. 질문사항 몇가지만 적어놓았습니다!

2024-02-29 11:26 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/entity/Community.java
> +    @OneToMany(mappedBy = "community", cascade = CascadeType.ALL)
중간테이블에서 삭제되더라구요

2024-02-29 11:49 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/community/repository/CommunityQuerydslRepository.java
> +        while (results.size() <= 10) {
![image](https://github.com/devridge-team-project/devridge-server/assets/108410827/7503207b-fdaa-46c2-a191-32635e120f60)
게시글 목록에서 hashtag를 이렇게 리스트로 받아야 프론트에서 하나의 데이터에서 사용할 수 있어서 이렇게 했습니다.
응답값이 id가 76인데 hashtag만 다르게 4번 나가기까지 하면  프론트에서 사용도 불편하고 속도나 네트워크 문제도 생겨서 제가 찾아본선에서는 지금 이게 최선인것같습니다.
이후에 더 찾아볼게요

2024-02-29 11:54 UTC, 213kky commented on api-module/src/main/java/org/devridge/api/domain/skill/entity/ProjectSkill.java
> +    @ManyToOne(fetch = FetchType.LAZY)
실수로 빼 먹은것 같네요
수정했습니다.

2024-02-29 12:09 UTC, yu-heejin commented on api-module/src/main/java/org/devridge/api/domain/community/repository/CommunityQuerydslRepository.java
> +        while (results.size() <= 10) {
이부분은 기존 방식대로 find를 두번 하는 쪽이 더 나은 것 같네요.

2024-03-06 09:50 UTC, merged